### ISSUE TITLE
Helpful Hints in README

### ISSUE THREAD

**Issue by coderforlife** [pblesi/touch_light#3]
Add helpful hints for first-timers in the README:

- On a Mac/Linux machine you can do ``particle publish touch_event 0,1,70,`date +%s`,0`` to send a touch event to all of your devices. The `70` can be adjusted from 0 to 255 for the color to set the device to. For Windows there is likely a similar command line that can be used.
- You can listen for touch events by running ``particle subscribe``.

**Comment by joniemaximus** [comment]
what would the particle publish be for a windows cmd prompt, thanks for the work you've done to this project

**Comment by pblesi** [comment]
My guess would be `particle publish touch_event 0,1,70,(powershell -command "(New-TimeSpan -Start (Get-Date "01/01/1970") -End (Get-Date)).TotalSeconds"),0` but I can't test this as I do not have access to a windows machine.
